
default:
	@echo "make { all | clean | cleandist}"

all:
	make -C demos all

gnathtml:
	make -C src gnathtml
	make -C demos gnathtml

clean:
	make -C demos clean

cleandist: 
	make -C demos cleandist
