NAME=simple

.PHONY: all clean cleandist distclean help

help:
	@echo "make {all | clean | cleandist}"

all:
	make -C $(NAME) all

clean:
	make -C $(NAME) clean

cleandist distclean:
	make -C $(NAME) cleandist

