
default:
	@echo "make {conf2x11 | conf2w32 | all | libs | cleandist}"

all:
	make -C AdaSDL all
	make -C AdaSDL_generic all
	make -C framebuff all

cleandist:
	make -C AdaSDL cleandist
	make -C AdaSDL_generic cleandist
	make -C framebuff cleandist

clean:
	make -C AdaSDL clean
	make -C AdaSDL_generic clean
	make -C framebuff clean


