.PHONY: all clean cleandist distclean

default:
	@echo "make { all | clean | cleandist}"

all:
	make -C demos all

clean:
	make -C demos clean

cleandist distclean: 
	make -C demos cleandist
