
help:
	@echo "***********************************"
	@echo "* make [all] [clean] [cleandist]  *"
	@echo "***********************************"

all:
	make -C AdaTest all

clean:
	make -C AdaTest clean
	make -C bind_check clean

cleandist:
	make -C AdaTest cleandist
	make -C bind_check cleandist

